import { TarotCard } from '@/types/tarot';

/**
 * Danh sách các lá bài Tarot Major Arcana
 */
export const TAROT_CARDS: TarotCard[] = [
  {
    id: 0,
    name: "The Fool",
    nameVi: "Kẻ Khờ",
    image: "https://www.trustedtarot.com/img/cards/the-fool.png",
    meaning: "Sự khởi đầu mới, tinh thần phiêu lưu, tự do và không lo lắng về tương lai.",
  },
  {
    id: 1,
    name: "The Magician",
    nameVi: "Nhà Ảo Thuật",
    image: "https://www.trustedtarot.com/img/cards/the-magician.png",
    meaning: "Sức mạnh ý chí, sự sáng tạo và khả năng biến ước mơ thành hiện thực.",
  },
  {
    id: 2,
    name: "The High Priestess",
    nameVi: "Nữ Giáo Sĩ",
    image: "https://www.trustedtarot.com/img/cards/the-high-priestess.png",
    meaning: "Trực giác, sự thông thái nội tâm và tiềm thức.",
  },
  {
    id: 3,
    name: "The Empress",
    nameVi: "Hoàng Hậu",
    image: "https://www.trustedtarot.com/img/cards/the-empress.png",
    meaning: "Sự phong phú, sáng tạo và nuôi dưỡng.",
  },
  {
    id: 4,
    name: "The Emperor",
    nameVi: "Hoàng Đế",
    image: "https://www.trustedtarot.com/img/cards/the-emperor.png",
    meaning: "Quyền lực, cấu trúc và sự ổn định.",
  },
  {
    id: 5,
    name: "The Hierophant",
    nameVi: "Giáo Hoàng",
    image: "https://www.trustedtarot.com/img/cards/the-hierophant.png",
    meaning: "Truyền thống, sự tuân thủ và hướng dẫn tâm linh.",
  },
  {
    id: 6,
    name: "The Lovers",
    nameVi: "Cặp Đôi Yêu Nhau",
    image: "https://www.trustedtarot.com/img/cards/the-lovers.png",
    meaning: "Tình yêu, mối quan hệ hòa hợp và sự lựa chọn.",
  },
  {
    id: 7,
    name: "The Chariot",
    nameVi: "Cỗ Xe",
    image: "https://www.trustedtarot.com/img/cards/the-chariot.png",
    meaning: "Quyết tâm, ý chí mạnh mẽ và chiến thắng.",
  },
  {
    id: 8,
    name: "Strength",
    nameVi: "Sức Mạnh",
    image: "https://www.trustedtarot.com/img/cards/strength.png",
    meaning: "Lòng can đảm, kiên nhẫn và sức mạnh nội tâm.",
  },
  {
    id: 9,
    name: "The Hermit",
    nameVi: "Ẩn Sĩ",
    image: "https://www.trustedtarot.com/img/cards/the-hermit.png",
    meaning: "Sự tự vấn, chiêm nghiệm và tìm kiếm chân lý.",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    nameVi: "Bánh Xe Vận Mệnh",
    image: "https://www.trustedtarot.com/img/cards/wheel-of-fortune.png",
    meaning: "Số phận, chu kỳ và những thay đổi không lường trước.",
  },
  {
    id: 11,
    name: "Justice",
    nameVi: "Công Lý",
    image: "https://www.trustedtarot.com/img/cards/justice.png",
    meaning: "Sự công bằng, trung thực và trách nhiệm.",
  },
  {
    id: 12,
    name: "The Hanged Man",
    nameVi: "Người Treo Ngược",
    image: "https://www.trustedtarot.com/img/cards/the-hanged-man.png",
    meaning: "Sự hy sinh, từ bỏ và nhìn nhận mọi việc từ góc độ mới.",
  },
  {
    id: 13,
    name: "Death",
    nameVi: "Tử Thần",
    image: "https://www.trustedtarot.com/img/cards/death.png",
    meaning: "Sự kết thúc, thay đổi và chuyển hóa.",
  },
  {
    id: 14,
    name: "Temperance",
    nameVi: "Tiết Độ",
    image: "https://www.trustedtarot.com/img/cards/temperance.png",
    meaning: "Sự cân bằng, kiên nhẫn và hòa hợp.",
  },
  {
    id: 15,
    name: "The Devil",
    nameVi: "Quỷ Dữ",
    image: "https://www.trustedtarot.com/img/cards/the-devil.png",
    meaning: "Sự ràng buộc, vật chất và những ham muốn trần tục.",
  },
  {
    id: 16,
    name: "The Tower",
    nameVi: "Tháp Sét",
    image: "https://www.trustedtarot.com/img/cards/the-tower.png",
    meaning: "Sự sụp đổ bất ngờ, khủng hoảng và giải phóng.",
  },
  {
    id: 17,
    name: "The Star",
    nameVi: "Ngôi Sao",
    image: "https://www.trustedtarot.com/img/cards/the-star.png",
    meaning: "Hy vọng, cảm hứng và sự bình yên tâm hồn.",
  },
  {
    id: 18,
    name: "The Moon",
    nameVi: "Mặt Trăng",
    image: "https://www.trustedtarot.com/img/cards/the-moon.png",
    meaning: "Ảo tưởng, sợ hãi và tiềm thức sâu thẳm.",
  },
  {
    id: 19,
    name: "The Sun",
    nameVi: "Mặt Trời",
    image: "https://www.trustedtarot.com/img/cards/the-sun.png",
    meaning: "Thành công, niềm vui và sự sống.",
  },
  {
    id: 20,
    name: "Judgement",
    nameVi: "Phán Xét",
    image: "https://www.trustedtarot.com/img/cards/judgement.png",
    meaning: "Sự tái sinh, tỉnh thức và đánh giá lại bản thân.",
  },
  {
    id: 21,
    name: "The World",
    nameVi: "Thế Giới",
    image: "https://www.trustedtarot.com/img/cards/the-world.png",
    meaning: "Sự hoàn thành, thành tựu và hoàn thiện.",
  },
]; 